name: Publish

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: yag000/open-dyslexic-latex

    steps:
      - uses: actions/checkout@main
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Build dyslexia file
        run: python scripts/dyslexia.py
      - name: Compile document
        run: lualatex integration-notes.tex
      - name: Compile Dyslexia document
        run: lualatex integration-notes-dyslexia.tex

      # From here it is copied from : https://github.com/jonhue/pubtex-action
      # with a few modifications
      - name: Move PDFs
        run: mv ./*.pdf dist
        shell: bash
      - name: Move index page
        run: cp README.md dist/index.md
        shell: bash
      - uses: actions/upload-artifact@master
        with:
          name: pdfs-deploy
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master

      - uses: actions/download-artifact@master
        with:
          name: pdfs-deploy
          path: dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: dist
          allow_empty_commit: true
          force_orphan: true
          enable_jekyll: true
